package no.nav.klage.domain

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Body for creating a sak. The id is generated by the server; an id sent by older clients is ignored.
 *
 * Only [fagsakId] and [fnr] are required. The other fields are nullable, and a missing or `null`
 * value is replaced with the value from [SakDefaults] in `SakService.createSak`. They are nullable,
 * rather than having the defaults as Kotlin default values, because the app deserializes with
 * Jackson 3 without a Kotlin module, so Kotlin default values would not be applied.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class CreateSakInput(
    @JsonProperty(required = true)
    val fagsakId: String,
    @JsonProperty(required = true)
    val fnr: String,
    val tema: String? = null,
    val utfall: Utfall? = null,
    val enhetsnummer: String? = null,
    val vedtaksdatoAsString: String? = null,
    val svardatoAsString: String? = null,
    val sakstype: Sakstype? = null,
    val status: SakStatus? = null,
    val saksbehandlerIdent: String? = null,
    val typeResultat: TypeResultat? = null,
    val nivaa: Nivaa? = null,
)
